/**************************************************************************************************************
* 7Summits
* Name: x7S_TestConstants
* Description: Hosts constants used intest classes
* Created By: [Lucas Soderstrom] (7Summits)
***************************************************************************************************************/
public class x7S_TestConstants {
    
    // Utility
    public static final string SOURCE_ORG_Name_SB = 'deluxesb';
    public static final string SOURCE_ORG_Name_FS = 'deluxefs';
    public static final string PRIMARY_LEGACY_ID = '0011400001cz9c4BBB';
    public static final string SECONDARY_LEGACY_ID = '0011400001cz9c4BBC';
    
    // Opportunity create field
    public static final string TEST_OPPORTUNITY_NAME = 'Test Opportunity';
    public static final string OPP_SEGMENT_MOS = 'MOS';
    public static final string OPP_STAGE_NAME_VALUE_FIT = 'Plan';
    public static final string OPP_TYPE_NEW_BUSINESS = 'New Business';

	// Contact create field
    public static final string CONTACT_EMAIL = 'test@test.com';
    public static final string CONTACT_SECOND_EMAIL = 'test1@test.com';
    public static final string CONTACT_THIRD_EMAIL = 'test2@test.com';    
    
    // Product create fields
    public static final string TEST_PRODUCT_NAME = 'Test Product';
    public static final string TEST_LEGACY_CODE_RT  = 'Major Accounts Opportunity/COD Opportunity';
    public static final string PRODUCT_FAMILY_CLOUD = 'Cloud';
    public static final string PRODUCT_GROUP_BUS_MARKETING_SERVICES = 'Business Marketing Services';
    public static final string PRODUCT_GROUP_DEL_MARKETING_SERVICES = 'Deluxe Marketing Services';
    public static final string PRODUCT_COMPONENT_SEFLSERACQUISITION = 'Self Service Acquisition';
    public static final string PRODUCT_OPP_REC_TYPE_Major_COD = 'Major Accounts Opportunity/COD Opportunity';
    
    // Account create fields
    public static final string TEST_ACCOUNT_NAME = 'Test Account';
    public static final string ACCOUNT_TYPE_CUST = 'Customer';
    public static final string ACCOUNT_CUST_TYPE_COMM_BANK = 'Commercial Bank';
    public static final string ACCOUNT_STATUS_ACTIVE = 'Active';
    public static final string ACCOUNT_LEGACY_REC_TYPE_MAJOR = 'Major Accounts';
    
    // User create fields
    public static final string OPP_CONTACT_ROLE_BU = 'Business User';
    public static final string OPP_CONTACT_ROLE_DM = 'Decision Maker';
    public static final string USER_EMAIL = 'standarduser@testorg.com';
    public static final string TEST_USER_FIRST_NAME = 'Testfirst';
    public static final string TEST_USER_LAST_NAME = 'Testlast';
    public static final string PROFILE_DX_ADMIN = 'Dx System Admin';
    public static final string PROFILE_DX_SALES_REP = 'Dx Enterprise Direct Sales Rep';
}